import React, { useState, useEffect } from 'react';
import { useAuth } from '../../contexts/AuthContext';
import { getCompanyProfile } from '../../utils/companyProfile';
import { LayoutDashboard, Building2, Users, UserCheck, Wallet, BookOpen, BarChart3, Settings, LogOut, Calculator } from 'lucide-react';
const NAV=[{group:'Overview',items:[{key:'dashboard',icon:LayoutDashboard,label:'Dashboard'},{key:'projects',icon:Building2,label:'Projects'}]},{group:'People',items:[{key:'clients',icon:Users,label:'All Clients'},{key:'investors',icon:UserCheck,label:'Investors'}]},{group:'Finance',items:[{key:'payments',icon:Wallet,label:'Payments'},{key:'ledger',icon:BookOpen,label:'Finance Ledger'},{key:'reports',icon:BarChart3,label:'Reports'},{key:'calculator',icon:Calculator,label:'Land Calculator'}]},{group:'System',items:[{key:'account',icon:Settings,label:'Settings'}]}];
const A='#007AFF';
export default function Sidebar({active,onChange,onClose}){
  const {user,logout}=useAuth();const[lo,setLo]=useState(false);const[hv,setHv]=useState(null);
  const[companyName,setCompanyName]=useState('');
  useEffect(()=>{ if(user?.uid) getCompanyProfile(user.uid).then(p=>setCompanyName(p.realEstateCompanyName||'')); },[user]);
  const ini=(user?.displayName||user?.email||'U').slice(0,2).toUpperCase();const un=user?.displayName||user?.email?.split('@')[0]||'User';
  async function hl(){setLo(true);await logout();}function hn(k){onChange(k);onClose&&onClose();}
  return(<div style={{width:240,height:'100%',display:'flex',flexDirection:'column',background:'rgba(255,255,255,0.92)',backdropFilter:'blur(24px) saturate(180%)',WebkitBackdropFilter:'blur(24px) saturate(180%)',borderRight:'1px solid rgba(0,0,0,0.07)'}}>
    <div style={{padding:'16px 14px 12px',borderBottom:'1px solid rgba(0,0,0,0.05)'}}><div style={{display:'flex',alignItems:'center',gap:10}}><div style={{width:36,height:36,borderRadius:11,background:A,display:'flex',alignItems:'center',justifyContent:'center',flexShrink:0,boxShadow:'0 3px 12px rgba(0,122,255,0.25)'}}><svg width="19" height="19" viewBox="0 0 24 24" fill="none" stroke="white" strokeWidth="2.2" strokeLinecap="round" strokeLinejoin="round"><path d="M3 21h18M5 21V7l8-4v18M19 21V11l-6-4"/></svg></div><div><div style={{fontSize:15.5,fontWeight:800,color:'#000',letterSpacing:'-0.03em',lineHeight:1}}>{companyName||'Layout ERP'}</div><div style={{fontSize:10.5,color:'#8E8E93',marginTop:2,fontWeight:500}}>Real Estate</div></div></div></div>
    <nav style={{flex:1,padding:'6px 6px 4px',overflowY:'auto'}}>{NAV.map(g=>(<div key={g.group} style={{marginBottom:2}}><p style={{fontSize:10.5,fontWeight:700,color:'#8E8E93',textTransform:'uppercase',letterSpacing:'0.08em',padding:'10px 10px 5px'}}>{g.group}</p>{g.items.map(it=>{const ia=active===it.key;const ih=hv===it.key&&!ia;const Ic=it.icon;return(<button key={it.key} onClick={()=>hn(it.key)} onMouseEnter={()=>setHv(it.key)} onMouseLeave={()=>setHv(null)} style={{width:'100%',display:'flex',alignItems:'center',gap:10,padding:'8px 10px',borderRadius:9,border:'none',background:ia?'rgba(0,122,255,0.09)':ih?'#F4F6FB':'transparent',color:ia?A:ih?'#000':'#3C3C43CC',fontWeight:ia?600:400,fontSize:13.5,marginBottom:1,cursor:'pointer',fontFamily:'inherit',textAlign:'left',transition:'all 0.13s',borderLeft:'3px solid '+(ia?A:'transparent')}}><Ic size={15} color={ia?A:'#8E8E93'} strokeWidth={ia?2:1.7}/><span style={{flex:1}}>{it.label}</span>{ia&&<div style={{width:5,height:5,borderRadius:'50%',background:A,flexShrink:0}}/>}</button>);})}</div>))}</nav>
    <div style={{padding:'8px 8px 12px',borderTop:'1px solid rgba(0,0,0,0.05)'}}><div style={{display:'flex',alignItems:'center',gap:9,padding:'9px 10px',borderRadius:10,background:'rgba(118,118,128,0.06)',marginBottom:8}}><div style={{width:32,height:32,borderRadius:'50%',flexShrink:0,overflow:'hidden',background:'linear-gradient(135deg,#007AFF,#5856D6)',display:'flex',alignItems:'center',justifyContent:'center',color:'#fff',fontWeight:700,fontSize:11.5}}>{user&&user.photoURL?<img src={user.photoURL} alt="" style={{width:32,height:32,objectFit:'cover'}}/>:ini}</div><div style={{flex:1,minWidth:0}}><div style={{fontSize:12.5,fontWeight:600,color:'#000',overflow:'hidden',textOverflow:'ellipsis',whiteSpace:'nowrap'}}>{un}</div><div style={{display:'flex',alignItems:'center',gap:4,marginTop:1}}><div style={{width:5,height:5,borderRadius:'50%',background:'#34C759'}}/><span style={{fontSize:10,color:'#8E8E93'}}>Active session</span></div></div></div>
    <button onClick={hl} disabled={lo} style={{width:'100%',display:'flex',alignItems:'center',gap:8,padding:'8px 10px',borderRadius:9,border:'1px solid rgba(0,0,0,0.08)',background:'transparent',color:'#3C3C43CC',cursor:lo?'not-allowed':'pointer',fontSize:12.5,fontWeight:500,fontFamily:'inherit'}}><LogOut size={14}/>{lo?'Signing out…':'Sign out'}</button></div>
  </div>);
}
